### ISSUE TITLE
Unclear input field

### ISSUE THREAD

**Issue by etu** [OrangeFlash81/proton-city#1]
I find the input field on https://proton.city/ unclear.

When I go there I get a big message that tell me to `Type the name of the game.`, when I do that nothing happened. So I tried to click on that instruction since it's underlined which is quite common on websites for input fields that has a placeholder.

That didn't do anything.

Then I found the huge gray box above that I didn't register as an input field until much later.

I have some suggestions to improve this:
1) Make the inputbox white instead of gray, since the background isn't white it's quite visible.
2) Add the instruction as a placeholder attribute on the input field instead of a div after

And possibly but less important

3) Auto focus on the input field so people can type without clicking a confusing gray box

Thanks for an awesome website :smile: 

Here I changed the color of the field, added placeholder and removed the instruction below with my firefox inspector:
![image](https://user-images.githubusercontent.com/461970/44782317-1c633b00-ab87-11e8-9dad-4f2359f99a59.png)

**Comment by AaronC81** [comment]
This is a really nice change! I'll definitely implement this once the site's working again. I said it on Reddit but I'll repeat it here; all your visits absolutely smashed through my Firebase free quota, so I'm reimplementing the site to use something else. I'll implement this change once that's done. Thanks for your feedback!

**Comment by AaronC81** [comment]
This is now implemented and live.
