### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by ian-bertolacci** [OrangeFlash81/proton-city#2]
It would be nice to be able to have a URL to direct people to the 'page' of a game, instead of telling them to search a term and click on the right one.

**Comment by AaronC81** [comment]
Great idea! I'll implement this shortly.

**Comment by OrangeFlash81** [comment]
This has been implemented now: 
![image](https://user-images.githubusercontent.com/3321773/44869196-dee4d780-ac84-11e8-9b25-4c6278ea21b8.png)

**Comment by AaronC81** [comment]
This is now implemented:
![image](https://user-images.githubusercontent.com/3321773/44869264-118ed000-ac85-11e8-958f-852688ce7fc3.png)
