### ISSUE TITLE
Text color not set in CSS

### ISSUE THREAD

**Issue by tastytea** [OrangeFlash81/proton-city#4]
The `html, body` section in `style.css` should have a `color` defined.
![screenshot_2018-09-01t11 09 34](https://user-images.githubusercontent.com/3681516/44944469-d3012e80-adc6-11e8-984c-67d9f1d8ecf9.png)

**Comment by AaronC81** [comment]
Thanks for pointing this out! I'll get on this. What browser are you using?

**Comment by tastytea** [comment]
Firefox 61 with system colors as default colors. In my case system colors are #D3DAE3 on #383C4A.

**Comment by AaronC81** [comment]
Ah, OK. I'll fix this shortly. Thanks for reporting this.
