### ISSUE TITLE
My Games not working after sign-in

### ISSUE THREAD

**Issue by dax-dev** [OrangeFlash81/proton-city#5]
After signing in to my Steam account, it says in the top-right of the site that I am signed in and displays my Steam display name.

When I navigate to "My Games", it still says "You need to sign in first".

**Comment by dax-dev** [comment]
Update: Turns out it was just wasn't able to query the Steam API I guess. Maybe you should show something different if the user is logged in but the content can't be retrieved yet.

**Comment by AaronC81** [comment]
I'll add some more checks. Is your Steam profile private? I don't think I've implemented checks for that.

**Comment by dax-dev** [comment]
Nope, I set them to Public before I signed in.

**Comment by dax-dev** [comment]
It worked after a little while once I visited the site again.

**Comment by dax-dev** [comment]
It looks like your code assumes that if no owned games can be retrieved from the API, then the user isn't signed in. Should probably put these as separate checks.

**Comment by AaronC81** [comment]
It takes a little while for a privacy change to take effect I believe, which might be why it worked later. I'll add separate checks like you suggest. Thanks for raising this!

**Comment by AaronC81** [comment]
Should now be fixed.
